// The strict check: refuse a message the contract does not describe exactly.
//
// The generated schemas the SDK parses with are forward-compatible on purpose: they drop a
// field they do not know, so a newer peer does not break an older reader. A conformance
// harness wants the opposite — an unknown or misspelled field is the defect it is looking
// for — and it wants the cross-field rules the proto states, which no per-field schema can
// express. This module is that check, and it is the only one: the client's strict decoding
// of a success answer, its check of every ErrorDetail in an error envelope, and the
// document readers in ../resolvers all call strictViolation. A message is checked against:
//
//   - the published STRICT JSON Schema of its message (gen/jsonschema, additionalProperties
//     false on every message object at every depth), so the shape is the one the
//     generator emitted rather than a second definition kept here;
//   - the cross-field rules, through crossFieldRuleIds, on the message itself and on every
//     nested message that carries any.
//
// The schema of every message the SDK checks by name is compiled at build time
// (gen/ts/strict, generated by scripts/gen-sdk-types.sh), so checking one generates no
// code at run time: an edge runtime such as Cloudflare Workers refuses code built from
// strings. Only a schema a caller passes to checkStrict is compiled at run time, with ajv,
// which therefore works on a runtime that allows it and not on one that does not.
//
// A null member of a message object is removed first: proto-JSON reads null as "absent",
// and a peer rendering unpopulated fields emits one for every unset message field.
// Nothing inside a google.protobuf.Struct is touched, because there a null is data.

import Ajv2020Module, { type ValidateFunction } from "ajv/dist/2020.js";

import { STRICT_MESSAGES } from "../../../gen/ts/strict/index.ts";
import { StrictViolation, violationOf } from "./strict-core.ts";

export { StrictViolation } from "./strict-core.ts";

// Ajv is CommonJS. Node hands an ESM importer its module.exports, which is the class; a
// bundler may hand over the namespace, whose `default` is. Read whichever arrived, typed
// by the one method used, so the declaration holds under either module resolution.
interface AjvEngine {
	compile(schema: object): ValidateFunction;
}
type AjvConstructor = new (options: {
	strict: boolean;
	validateFormats: boolean;
	addUsedSchema: boolean;
}) => AjvEngine;
const Ajv2020 = ((Ajv2020Module as unknown as { default?: unknown }).default ??
	Ajv2020Module) as unknown as AjvConstructor;

// One engine for the process, built on the first caller-given schema. The options are
// the ones gen/ts/strict is compiled with: strict, `format` an annotation (asserting
// `duration` would need ajv-formats), and addUsedSchema false, so a schema is never
// registered under its $id and a caller's copy of a schema the SDK also bundles compiles
// beside it instead of colliding with it.
let engine: AjvEngine | undefined;

function ajv(): AjvEngine {
	engine ??= new Ajv2020({ strict: true, validateFormats: false, addUsedSchema: false });
	return engine;
}

/**
 * checkStrict refuses `payload` unless it is a `message` the strict contract accepts.
 *
 * `message` is the fully-qualified message name, for example "fora.v1.WellKnownManifest",
 * and `payload` the decoded proto-JSON value, as JSON.parse returns it. Throws
 * StrictViolation naming the first failure: the location and the schema's complaint for
 * an unknown field or a field-level rule, or the violated rule ids for a cross-field rule.
 *
 * The SDK bundles the strict schema of every message it reads. For any other message,
 * pass its strict schema, as published at
 * `@fora-protocol/sdk/jsonschema/<message>.schema.strict.json`; a message with neither
 * throws a plain Error, which says nothing about the payload.
 */
export function checkStrict(message: string, payload: unknown, schema?: object): void {
	const problem = strictViolation(payload, message, schema);
	if (problem !== undefined) throw new StrictViolation(message, problem);
}

/**
 * strictViolation says why `raw` is not a `message` the strict contract accepts: the
 * location and the schema's complaint, or the cross-field rules it breaks. Undefined when
 * it is accepted.
 */
export function strictViolation(raw: unknown, message: string, given?: object): string | undefined {
	if (given !== undefined) {
		return violationOf(raw, message, given as Readonly<Record<string, unknown>>, compileOnce(given));
	}
	const strict = STRICT_MESSAGES[message];
	if (strict === undefined) throw new Error(`no strict schema for ${message}`);
	return violationOf(raw, message, strict.schema, strict.validate);
}

// A schema a caller passed is compiled once per object, never cached under a name a
// bundled schema could share.
const compiledGiven = new WeakMap<object, ValidateFunction>();

function compileOnce(schema: object): ValidateFunction {
	let validate = compiledGiven.get(schema);
	if (validate === undefined) {
		validate = ajv().compile(schema);
		compiledGiven.set(schema, validate);
	}
	return validate;
}
