#!/usr/bin/env node
// Route-retirement gate.
//
// The link validator in the Astro build covers links *inside* the site: break
// one and the build fails. It cannot see the other half — a link held by
// someone else. A post, a partner's page, a search index. Rename a slug and
// every one of those 404s, with nothing here noticing.
//
// So the built route set is committed as routes.txt, and this compares the set
// on main against the set here. A route that disappeared must be answered by a
// rule in redirects.json, which amplify.yml applies on deploy. Committing the
// manifest is what makes the loss visible: the removed URL appears in the pull
// request diff, beside the change that removed it.
//
//   node scripts/routes.mjs write   regenerate routes.txt from dist/
//   node scripts/routes.mjs check   verify the manifest is current and that
//                                   every retired route has a redirect
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const WEBSITE = dirname(dirname(fileURLToPath(import.meta.url)));
const DIST = join(WEBSITE, 'dist');
const MANIFEST = join(WEBSITE, 'routes.txt');
const REDIRECTS = join(WEBSITE, 'redirects.json');
const BASE_REF = process.env.ROUTES_BASE_REF ?? 'origin/main';

const HEADER = [
	'# Every URL this site serves, one per line, sorted.',
	'# Generated by `npm run routes` in website/. Do not hand-edit.',
	'#',
	'# A line that disappears is a URL that stops answering. If anything outside',
	'# this repository links to it, that link breaks. Retiring one therefore needs',
	'# a rule in redirects.json — see docs/retiring-a-url.md.',
];

/** Every route the build emitted, as a sorted list of `/path/` strings. */
export async function builtRoutes(dist = DIST) {
	const out = [];
	async function walk(dir) {
		for (const entry of await readdir(dir, { withFileTypes: true })) {
			const full = join(dir, entry.name);
			if (entry.isDirectory()) await walk(full);
			else if (entry.name === 'index.html') {
				const rel = relative(dist, dirname(full)).split('\\').join('/');
				out.push(rel === '' ? '/' : `/${rel}/`);
			}
		}
	}
	await walk(dist);
	return [...new Set(out)].sort();
}

/** Manifest lines, minus comments and blanks. */
export function parseManifest(text) {
	return text
		.split('\n')
		.map((l) => l.trim())
		.filter((l) => l && !l.startsWith('#'))
		.sort();
}

/** The `source` of every redirect rule, normalised without a trailing slash. */
export function redirectSources(json) {
	const rules = JSON.parse(json);
	if (!Array.isArray(rules)) throw new Error('redirects.json must be a JSON array of rules');
	return new Set(
		rules.map((rule, i) => {
			if (!rule || typeof rule.source !== 'string' || typeof rule.target !== 'string') {
				throw new Error(`redirects.json rule ${i} needs both a source and a target`);
			}
			return rule.source.replace(/\/$/, '') || '/';
		}),
	);
}

/** Routes present in `base` and gone from `current`, that no rule answers. */
export function uncoveredRetirements(base, current, sources) {
	const live = new Set(current);
	return base
		.filter((r) => !live.has(r))
		.filter((r) => !sources.has(r.replace(/\/$/, '') || '/'));
}

function manifestOnBase() {
	try {
		return parseManifest(
			execFileSync('git', ['show', `${BASE_REF}:website/routes.txt`], {
				cwd: WEBSITE,
				encoding: 'utf8',
				stdio: ['ignore', 'pipe', 'ignore'],
			}),
		);
	} catch {
		return null; // base carries no manifest yet
	}
}

function requireDist() {
	if (!existsSync(DIST)) {
		console.error('routes: website/dist not found — run the site build first');
		process.exit(1);
	}
}

async function write() {
	requireDist();
	const routes = await builtRoutes();
	writeFileSync(MANIFEST, [...HEADER, ...routes].join('\n') + '\n');
	console.log(`routes: wrote routes.txt (${routes.length} routes)`);
}

async function check() {
	requireDist();
	const current = await builtRoutes();
	let failed = false;

	if (!existsSync(MANIFEST)) {
		console.error('::error::website/routes.txt is missing — run `npm run routes` and commit it');
		process.exit(1);
	}

	const committed = parseManifest(readFileSync(MANIFEST, 'utf8'));
	if (committed.join('\n') !== current.join('\n')) {
		console.error('::error::website/routes.txt is stale — run `npm run routes` and commit it');
		const live = new Set(current), known = new Set(committed);
		for (const r of current.filter((r) => !known.has(r))) console.error(`  built, not in the manifest: ${r}`);
		for (const r of committed.filter((r) => !live.has(r))) console.error(`  in the manifest, not built: ${r}`);
		failed = true;
	}

	const base = manifestOnBase();
	if (base === null) {
		console.log(`routes: ${BASE_REF} carries no manifest yet — retirement check skipped`);
		process.exit(failed ? 1 : 0);
	}

	const sources = redirectSources(existsSync(REDIRECTS) ? readFileSync(REDIRECTS, 'utf8') : '[]');
	const uncovered = uncoveredRetirements(base, current, sources);
	if (uncovered.length) {
		console.error(
			'::error::these URLs answered on ' + BASE_REF + ' and answer nothing now. ' +
			'Add a rule to website/redirects.json for each, or keep the route:',
		);
		for (const r of uncovered) console.error(`  ${r}`);
		failed = true;
	}

	if (!failed) console.log(`routes: clean — ${current.length} routes, nothing retired without a redirect`);
	process.exit(failed ? 1 : 0);
}

// Only dispatch when run directly. The named exports above are imported by
// routes.test.mjs, and a bare import must not execute anything.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	const cmd = process.argv[2];
	if (cmd === 'write') await write();
	else if (cmd === 'check') await check();
	else {
		console.error('usage: node scripts/routes.mjs write|check');
		process.exit(2);
	}
}
